extends: "@redhat-cloud-services/eslint-config-redhat-cloud-services"
globals:
  insights: 'readonly'
  shallow: readonly
  render: 'readonly'
  mount: 'readonly'

rules:
  # Specify whether double or single quotes should be used in JSX attributes
  # https://eslint.org/docs/rules/jsx-quotes
  jsx-quotes:
    - error
    - prefer-double

  # Validate closing tag location in JSX
  # https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-closing-tag-location.md
  react/jsx-closing-tag-location:
    - error

  # Validate props indentation in JSX
  # https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-indent-props.md
  react/jsx-indent-props:
    - error
    - 2

  # Enforce props alphabetical sorting
  # https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-sort-props.md
  react/jsx-sort-props: [2, {
    ignoreCase: true,
    callbacksLast: false,
    shorthandFirst: false,
    shorthandLast: false,
    noSortAlphabetically: false,
    reservedFirst: true,
  }]

  # Enforce propTypes declarations alphabetical sorting
  # https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/sort-prop-types.md
  react/sort-prop-types: [1, {
    ignoreCase: true,
    callbacksLast: false,
    requiredFirst: false,
    sortShapeProp: true,
  }]

  # Enforce defaultProps declarations alphabetical sorting
  # https://github.com/jsx-eslint/eslint-plugin-react/blob/843d71a432baf0f01f598d7cf1eea75ad6896e4b/docs/rules/jsx-sort-default-props.md
  react/jsx-sort-default-props: 
    - 1
    - ignoreCase: true
  
  # Specify alphabetical order of members within declarations
  # https://eslint.org/docs/latest/rules/sort-imports
  sort-imports: 
    - 2
    - ignoreDeclarationSort: true

  # Require that the first prop in a JSX element be on a new line when the element is multiline
  # https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-first-prop-new-line.md
  react/jsx-first-prop-new-line:
    - error
    - multiline-multiprop

  # Enforce spacing around jsx equals signs
  # https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-equals-spacing.md
  react/jsx-equals-spacing:
    - error
    - never

  # Enforce JSX indentation
  # https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-indent.md
  react/jsx-indent: 
    - error
    - 2
