extends: "@redhat-cloud-services/eslint-config-redhat-cloud-services"
globals:
  insights: 'readonly'
  shallow: readonly
  render: 'readonly'
  mount: 'readonly'
rules:
  sort-imports:
    - error
    - ignoreDeclarationSort: true
