apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/RedHatInsights/frontend-starter-app?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch
      == "master"
    pipelinesascode.tekton.dev/pipeline: https://raw.githubusercontent.com/catastrophe-brandon/konflux-pipelines/fda9a7eafca825083d50ffadf149f944a3ebd4b3/pipelines/platform-ui/docker-build-run-all-tests.yaml
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: frontend-starter-app
    appstudio.openshift.io/component: frontend-starter-app
    pipelines.appstudio.openshift.io/type: build
  name: frontend-starter-app-on-pull-request
  namespace: rh-platform-experien-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/rh-platform-experien-tenant/frontend-starter-app/frontend-starter-app:on-pr-{{revision}}
  - name: image-expires-after
    value: 5d
  - name: dockerfile
    value: build-tools/Dockerfile
  - name: path-context
    value: .
  - name: rebuild
    value: "true"
  - name: e2e-app-port
    value: "8000"
  - name: unit-tests-script
    value: |
      #!/bin/bash
      set -ex

      npm install
  - name: run-app-script
    value: |
      #!/bin/sh
      # Script that runs the test application with Caddy using ConfigMap-mounted Caddyfile

      set -e

      echo "Starting application with Caddy using ConfigMap Caddyfile..."
      exec caddy run --config /etc/caddy/Caddyfile
  - name: e2e-tests-script
    value: |
      #!/bin/bash
      set -ex

      echo "E2E_USER is ${E2E_USER}"
      getent hosts stage.foo.redhat.com
      timeout 120s bash -c 'until curl -k https://stage.foo.redhat.com:1337 > /dev/null 2>&1; do
        echo "Waiting for dev server to be ready"
        sleep 5
      done'
      echo "Dev server ready!"

      echo "Installing Playwright browsers..."
      ./node_modules/.bin/playwright install --with-deps

      echo "Running Playwright tests ..."
      ./node_modules/.bin/playwright test
  - name: e2e-credentials-secret
    value: frontend-starter-app-credentials-secret
  - name: frontend-proxy-routes-configmap
    value: frontend-starter-app-dev-proxy-caddyfile-v2
  pipelineRef:
    resolver: git
    params:
    - name: url
      value: https://github.com/catastrophe-brandon/konflux-pipelines
    - name: revision
      value: fda9a7eafca825083d50ffadf149f944a3ebd4b3
    - name: pathInRepo
      value: pipelines/platform-ui/docker-build-run-all-tests.yaml
  taskRunTemplate:
    serviceAccountName: build-pipeline-frontend-starter-app
  workspaces:
  - name: workspace
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 3Gi
      status: {}
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
